### ISSUE TITLE
Facebook route always "empty"

### ISSUE THREAD

**Issue by moliv68** [DIYgod/RSSHub#7512]
Hi.  

Running locally on new docker instance. Other routs are working but Facebook always returns:
Looks like something went wrong
Route requested: /facebook/page/SonetPCR
Error message: this route is empty, please check the original site or create an issue

Thanks in advance for the help.

**Comment by moliv68** [comment]
No. Solved with a different solution. https://rss.app

**Comment by WladyX** [comment]
aha, cool, i've switched to rss-bridge, very happy so far.

**Comment by bullride** [comment]
> aha, cool, i've switched to rss-bridge, very happy so far.

@WladyX  Are you serious? RSS-Bridge? Facebook bridge been giving problems the past 2 months.

**Comment by WladyX** [comment]
It seems to give some errors, but it also catches the posts it seems, so in my feed i get the FB posts + some erorrs, also i could not get twitter autentication on rsshub, but for rss bridge it's not needed.

**Comment by decentral1se** [comment]
Still facing this issue, unsure if I can add any new info (e.g. no new logs)... maybe https://github.com/DIYgod/RSSHub/pull/7377 can fix it? I opened up https://github.com/DIYgod/RSSHub/issues/10544 but closed as dupe...
